### ISSUE TITLE
Update TYPO3 Extension Repository

### ISSUE THREAD

**Issue by felixlohmeier** [subugoe/typo3-find#118]
Please update https://typo3.org/extensions/repository/view/find to latest version. Some people may stumble upon this. Thank you!

**Comment by ipf** [comment]
Thanks, that's indeed an issue for us. @ssp could you please transfer the TYPO3 find extension key to me? Thanks a lot!

**Comment by cedricziel** [comment]
Maybe that's a good point to throw the submodules away ;)

**Comment by ipf** [comment]
@ssp and participants, what do you think, should we still use TER as distribution channel?

**Comment by ipf** [comment]
There won't be any TER releases anymore for the find extension. Please use composer for installing this extension
