### ISSUE TITLE
Doesnt work with TYPO3 v8.*

### ISSUE THREAD

**Issue by AppWerft** [subugoe/typo3-find#125]
Hi,
today (beginning of March 2018) v9 is the current version and by using of v8 we cannot use your awesome module because of PHP limitation. T3 v8 nee3ds PHP7.2 and your support ends with 7.0.99

In Detail: 
It crashes find/ext_localconf.php#L7 with:
```
Tue Mar 06 17:01:51.427816 2018] [php7:error] [pid 15885] [client ::1:53100] PHP Fatal error:  require_once(): Failed opening required '/Library/WebServer/Documents/T3/typo3conf/ext/find/.Build/vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/T3/typo3conf/ext/find/ext_localconf.php on line 7
```
Any ideas to solve?

**Comment by AppWerft** [comment]
Thank you for your quick answer. I have used the extension from this github repo
Now I have started 
```
php /usr/local/bin/composer.phar install
```
as www user in folder of extension.
```
Generating autoload files
Generating  class alias map file
Inserting class alias loader into main autoload.php file
> mkdir -p .Build/Web/typo3conf/ext/
> [ -L .Build/Web/typo3conf/ext/find ] || ln -snvf ../../../../. .Build/Web/typo3conf/ext/find
```
After this I tried to activate your module in extension manager. Now the warning appeared with text about PHP version. I agreed. After this:
"Cannot set alias loader, as it is already registred!".
Whats going wrong?

**Comment by cedricziel** [comment]
please follow these steps:

1. reset your git clone: 

`git reset --hard origin/master`

2. create the `.Build` directory manually and change into it

`mkdir -p .Build && cd .Build`

3. grab solarium from packagist

* `composer init` (leave the defaults here, it doesnt matter)
* `composer require "solarium/solarium:~3.3"`

Afterwards, you should be able to flush the cache, a `vendor/autoload.php` file should be present in `.Build`.

**Comment by AppWerft** [comment]
Thanks, now I have this composer.json:
```
{
    "name": "fuerst/.build",
    "require": {
        "solarium/solarium": "~3.3"
    }
}
```
and in vendor are 18 subitems, solarium too. – and I can activate module without issues.
Now I will dive deeper. thanks for your help!! You saved my day.

**Comment by cedricziel** [comment]
Nice, have fun! :)

**Comment by AppWerft** [comment]
Unfortunately after adding the pluginto FE this error appears:
```
"Could not analyse class: "Subugoe\Find\Controller\SearchController" maybe not loaded or no autoloader? Class Subugoe\Find\Controller\SearchController does not exist "
```
Following this hint https://www.typo3.net/forum/thematik/zeige/thema/125936/ I have cleared the cache in install tool => same issue.  I'm working with v8.7.10 with PHP 7.2
I think something with autoloader is going wrong.

**Comment by cedricziel** [comment]
Obviously. Your autoloader has been damaged when it was dumped and this happens quite often when something goes wrong (f.e. building a localconf with errors). You can remove the autoloader by hand and have it regenerated.

**Comment by AppWerft** [comment]
Thanks this issue is solved.
Now I have added the plugin to page and added Find static template from extension.
In setup now is:
```
plugin.tx_find.settings {
        connections {
                default {
                        options {
                                host = 192.168.43.69
                                port = 8983
                                path = /solr/demo
                        }
                }
        }
        standardFields {
                title = type_s
                snippet = comment_t
        }
}
```
After cache cleaning I see:
`Oops, an error occurred! Code: 2018030711522924b9701d`.
It is not my day.  ;-(

**Comment by cedricziel** [comment]
What's the specific error?

**Comment by AppWerft** [comment]
https://gist.github.com/AppWerft/671b82f1941ee9592da4a282e38446e6

**Comment by cedricziel** [comment]
Cant reproduce this

**Comment by AppWerft** [comment]
I see this `SearchController.php` in module/Classes/Controllers folder.

**Comment by cedricziel** [comment]
So?

**Comment by AppWerft** [comment]
Now I have "restarted" the module: I have cleaned the folder. Then I checkout to Desktop. Adding the Solarium stuff and then copied to module (chown -R ...). Deacticated/activated and I see still this magic error message with the content:
```
ReflectionException: Class Subugoe\Find\Controller\SearchController 
does not exist in 
/Library/WebServer/Documents/T3/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php:
```
