### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by AppWerft** [subugoe/typo3-find#126]
In my TS I wrote:
```
facets {
                 5 {
                        id = BirthOfPaper
                        type = Histogram
                        field = publicationYear
                        query = publicationYear:%s
                        fetchMaximum=1000
                        barWidth=10
                }
 ```

And in source code of page I see:
```
<script type="text/javascript">
			(function () {
				var histogramConfiguration = {
					'facetID': &quot;BirthOfPaper&quot;,
					'barWidth': ,
					'activeFacets': [],
				}
				var facetData = {&quot;2003-01-01T00:00:00Z&quot;:302,&quot;2002-01-01T00:00:00Z&quot;:1};
    			        tx_find.createHistogramForTermsInContainer(facetData, document.getElementById('c-1-histogram-BirdOfPaper'), histogramConfiguration);
			})();
```
Observation:
All string values are escaped and number value like barwidth are missed and therefore I see issues on JS console. Whats going wrong? I think the issue is during  building of JS code from TS-code.

PS: in documentation I miss hint to embedding of JS snippets ;-)

**Comment by cedricziel** [comment]
In more recent versions of fluid, you have more fine-grained control over output escaping and a default escaping is applied. - We'd happily work on a pull request in case you can supply one.

If you have anything to add to the documentation - that would be awesome!

**Comment by AppWerft** [comment]
Hi,
thanx for quick answer at Friday. What can I do in relation to my converting issue? 
Second I will do a PR. ;-)

**Comment by cedricziel** [comment]
I believe the format viewhelpers in this extension (more generally every viewhelper that directly output something) need to have their `escapeOutput` property set to false.

**Comment by AppWerft** [comment]
is it a TS property or I have to modify PHP code?

**Comment by cedricziel** [comment]
PHP

**Comment by AppWerft** [comment]
There are 34 ViewHelpers in `Classes/ViewHelpers` ...

**Comment by AppWerft** [comment]
Here I see the template:

```
'facetID': <s:format.json data="{facetInfo.id}"/>,
	'barWidth': {f:if(condition:facetInfo.barWidth, then:facetInfo.barWidth else:1)},
	'activeFacets': [],
```
Which PHP snippet resolve this?

**Comment by cedricziel** [comment]
The used viewhelper needs adjustments as mentioned

**Comment by AppWerft** [comment]
You are right (sure), it is in relation to https://www.andrerinas.de/tutorials/typo3-8lts-viewhelper-default-escaping-ausschalten.html Now I'm hunting for the right class

**Comment by AppWerft** [comment]
I found a workaround by myself:
For TYPO3 >7  the stuff will default escaped.
Enclosing of stuff with 
```
<f:format.htmlentitiesDecode>
```
helps.
