### ISSUE TITLE
find in non composer mode

### ISSUE THREAD

**Issue by AppWerft** [subugoe/typo3-find#153]
We using a ready to use version of TYPO3 in non composer (classical) mode (https://t3bootstrap.de/de/home/).

In this case the rule 

`if (!defined('TYPO3_COMPOSER_MODE') || TYPO3_COMPOSER_MODE === false) {` 

inside `ext_localconf.php` is active.

Because there is no folder `.Build` inside the module an exception will thrown.

This code snippet:

```php
 require  \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/typo3_src/vendor/autoload.php';
```
throws the message:

`Class Subugoe\Find\Controller\SearchController does not exist. Reflection failed.` 

Any solutions? psr-4?

**Comment by AppWerft** [comment]
My observation:

The .Build folder will created by `composer.json` in section `scripts.post-autoload-dump`. But this script will only run in composer mode! Maybe this is the reason.

**Comment by ipf** [comment]
Hello @AppWerft,
thanks for the report, I will have a look at that!

**Comment by AppWerft** [comment]
Thanks.

Additional details:
in my ext_emconf.php:

```
 'autoload' => [
        'psr-4' => [
            ['Subugoe\\Find\\' => 'Classes'],
        ],
   ],
```
In extension folder is:  `Classes/Controller/SearchController.php`

But, this exception will thrown:

Class Subugoe\Find\Controller\SearchController does not exist. Reflection failed.

With this code in ext_localconf.php I call the autoloader:

```
require_once \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/typo3_src/vendor/autoload.php';
```

**Comment by AppWerft** [comment]
Next:
I can activate/deactivate in AdminTools/Extension/ 
But in AdminTools/Settings/Extension Configuration/ I cannot see the find extension.

**Comment by AppWerft** [comment]
This (inner) code snippet 
```php
if (!defined('TYPO3_COMPOSER_MODE') || TYPO3_COMPOSER_MODE === false) {
    require_once \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('find').'.Build/vendor/autoload.php';
}
```
will only run in classical mode. But in this mode the script inside `composer.json` (https://github.com/subugoe/typo3-find/blob/master/composer.json#L41-L46) will not executed and therefore the `.Build`  folder doesn't exist.

**Comment by AppWerft** [comment]
After 
```
composer dump-autoload -o
```
and reusing original 
```
require_once \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('find').'.Build/vendor/autoload.php'
```

this will thown:
```
(1/1) Error
Class 'Solarium\Client' not found
in /opt/sites/servers/openscience/web/typo3conf/ext/find/Classes/Service/SolrServiceProvider.php line 83
```

**Comment by AppWerft** [comment]
Inside `/var/www/servers/openscience/web/typo3_src/vendor/solarium/solarium`  is a `composer.json` and an autoload  section. Starting of `composer dump-autoload -o` created a vendor folder with `autoload.php` and `composer` folder.

**Comment by AppWerft** [comment]
Found solution:

```
/* build symlink to autoloader */
composer dump-autoload -o
/* install solarium */
composer update solarium/solarium
```
Link: https://stackoverflow.com/questions/16739998/how-to-update-a-single-library-with-composer
