### ISSUE TITLE
flooding TYPO3 sys_log

### ISSUE THREAD

**Issue by jkothe** [subugoe/typo3-find#91]
TYPO3 DB sys_log:
...
Core: Error handler (FE): PHP Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in /srv/www/chroot/vlib1/vlib1/htdocs/typo3conf/ext/find/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php line 148
...

In der Installation von <http://aac.sub.uni-goettingen.de> und in vielen anderen auch wird "open_basedir" eingesetzt, um die TYPO3 Instanzen zu kapseln.

**Comment by ipf** [comment]
Fixed upstream in solarium core
